### ISSUE TITLE
Extrinsic Hallucinations Ratio for Each System

### ISSUE THREAD

**Issue by anton164** [danton-nlp/factual-beam-search#102]
- for each example,
  - compute number of extrinsic factual hallucinations
  - compute number of extrinsic hallucinations
  - divide
- take average over all examples for each system

**Comment by dleve123** [comment]
In addition to https://github.com/danton-nlp/factual-beam-search/pull/108, please see this updated main results table and caption in the overleaf:



![Image](https://user-images.githubusercontent.com/1561546/173957842-5b7bc3e3-3fbc-4492-87ad-6c52be2c4fc7.png)

... upon review, I'll make the Ext. Ent. Factual the last column before the rouge scores.

**Comment by dleve123** [comment]
updated post column flipping

![Image](https://user-images.githubusercontent.com/1561546/173958246-7b0ee2d0-e012-4882-8132-7541bd619395.png)

**Comment by anton164** [comment]
Good work @dleve123 ! I think we can resolve this now

**Comment by anton164** [comment]
My bad - PR still in review

**Comment by dleve123** [comment]
Closed by #108
