### ISSUE TITLE
Finalize Analysis - Histogram for oracle fixes over number of GEF iterations

### ISSUE THREAD

**Issue by dleve123** [danton-nlp/factual-beam-search#54]
> “Reviewers will want precise numbers about speed and the number of BS iterations that you run.” 

We can say how long it took to generate summaries on our GPU for the test set (with oracle & classifier) relative to baseline (BART-Large). Is that sufficient? 

---

We think it'll be most meaningful / simpler to show the number of FBS iterations/example, instead of some wall clock timing.

**Comment by anton164** [comment]
Feedback from PR, moving back to Prioritized:
- Only show full
- Reduce vertical height
- Remove title, we use the caption in LATEX instead
- Remove 8-11 and replace 8 with 8+ / 7+
- Use same style as other plot
- Only include data for summaries which FBS can change?

**Comment by anton164** [comment]
Y axis: Summaries completed (explain in caption)
X axis: Number of iterations

**Comment by dleve123** [comment]
Updated here: https://github.com/danton-nlp/factual-beam-search/pull/138 -- moving this to in review
