### ISSUE TITLE
Freeze current test set ids, add test set for 100 random sample of xsum-test & eval with xsum-test-100 / xent-test-100, then decide

### ISSUE THREAD

**Issue by dleve123** [danton-nlp/factual-beam-search#56]
- no filtering of supported/unsupported xsum
- if we choose xsum-test, ensure it doesn't overlap with xent-train

**Comment by anton164** [comment]
Decision: two test-extrinsic sets (baseline/pegasus), reword it to ~"summaries where FBS can make changes".
